# Generated by Django 4.2.1 on 2023-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversetup',
            name='image',
            field=models.ImageField(upload_to='serversetup/images/'),
        ),
    ]
